import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      "en_US": {
        "login_with_pw": "Login with password",
        "login_via_otp": "Login via OTP",
        "Sorry_for_the_technical_Beakdown" :
        "Sorry for the technical Breakdown issue. We are here to help you. please wait while we resolve.",
        "payment_back":"Your transaction is under process , Are you sure you want to close this tab?",
        "Dont_have": "Don’t have an account yet?",
        "language": "English",
        "forgot_password": "Forgot Password",
        "otp": "OTP",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "submit": "Submit",
        "please_enter_otp": "Please enter OTP",
        "wrong_otp": "Wrong OTP",
        "please_enter_password": "Please enter password",
        "password_length": "Password length must be between 6–15 characters.",
        "password_should_be_same": "Password should be same",
        "welcome_back": "Welcome back",
        "email": "Email",
        "password": "Password",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "verification_code": "Verification Code",
        "You_deserve_the_best_Connecting_you_with_the_best_driver":
            "You deserve the best, Connecting you with the best driver",
        "continue": "Continue",
        "please_enter_valid_otp": "Please enter valid OTP",
        "didn_t_get_the_OTP": "Didn`t Get The OTP?",
        "resend_OTP": "Resend OTP ",
        "enter_phone": "Enter phone number to continue",
        "phone": "Phone",
        "Please_type_the_verification_code_sent_to_your":
            "Please type the verification code sent to your",
        "mobile_number": " Mobile Number",
        "Please_type_the_verification_code_sent_to_your_email":
            "Please type the verification code sent to your Email",
        "please_number.": "Please enter your mobile number.",
        "check_fare": "Check Fare",
        "sign_up": "Sign Up",
        "Or_continue_with": "Or Continue with",
        "create_account": "Create\nAccount",
        "first_name": "First Name",
        "last_name": "Last Name",
        "confirm_password": "Confirm Password",
        "i_have_read": "I have read and agreed the Terms and\nConditions.",
        "terms_condition": "Terms Conditions",
        "sign_in": "Sign In",
        "Don't-have_account?": "Don't have an account?",
        "are_sure_delete?": "Are sure you want to delete?",
        "no": "NO",
        "delete": "DELETE",
        "no_data_found..": "No data found..",
        "valid_till": "Valid Till",
        "remove": "Remove",
        "use_code": "Use Code",
        "dispute": "Dispute",
        "you": "You",
        "admin": "Admin",
        "driver_unprofessional": "Driver Unprofessional",
        "something_went_wrong...": "Something went wrong...",
        "please_dispute..": "Please select any dispute..",
        "dismiss": "Dismiss",
        "finding_driver...": "Finding driver...",
        "cancel_request": "Cancel Request",
        "invoice": "Invoice",
        "booking_id": "Booking ID",
        "time-Taken": "Time Taken",
        "base_fare": "Base Fare",
        "time_fare": "Time Fare",
        "distance_fare": "Distance Fare",
        "waiting_amount": "Waiting Amount",
        "toll_charges": "Toll Charges",
        "tips": "Tips",
        "add_tip": "Add Tip",
        "total": "Total",
        "wallet_detection": "Wallet Detection",
        "round_off": "Round Off",
        "discount": "Discount",
        "payable": "Payable",
        "payment_:_": "Payment : ",
        "change": "CHANGE",
        "payment_driver": "Payment not confirmed from the driver",
        "done": "Done",
        "pay_now": "Pay now",
        "lost_item": "Lost Item",
        "Mention_the_lost_item": "Mention the lost item",
        "please_details": "Please enter lost item details",
        "ratings_your_trip_with": "Ratings your trip with",
        "write_your_comment": "Write your comment",
        "reason_for_canceling": "Reason for canceling",
        "scan_the_number": "Scan the QR to fetch mobile number",
        "sos_alert": "SOS Alert",
        "are_you_sure_alert?":
            "Are you sure you want to proceed with emergency alert?",
        "yes": "YES",
        "time_taken": "Time Taken",
        "tax": "Tax",
        "close": "Close",
        "help": "Help",
        "support": "Support",
        "call": "Call",
        "message": "Message",
        "our_you_soon!": "Our team persons will contact you soon!",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Your Referral Code",
        "choose_one": "choose one",
        "referral_count :": "Referral Count :",
        "referral_amount:": "Referral Amount:",
        "notification_manager": "Notification Manager",
        "you_any_notification": "You don't have any notification",
        "passbook": "Passbook",
        "no_wallet_history": "No Wallet History",
        "amount": "Amount",
        "balance": "Balance : ",
        "lost_my_item": "Lost my item",
        "past_trip_details": "Past Trip Details",
        "pay_via": "Pay via",
        "comments": "Comments",
        "no_comments": "No Comments",
        "view_receipt": "View Receipt",
        "open": "OPEN",
        "payment_options": "Payment Options",
        "cash": "Cash",
        "by_cash": "By Cash",
        "card": "Card",
        "add": "Add",
        "payStack": "PayStack",
        "profile": "Profile",
        "phone_number": "Phone Number",
        "looking_to_change_password": "Looking to change password",
        "save": "Save",
        "setting": "Setting",
        "favorites": "Favorites",
        "home": "Home",
        "work": "Work",
        "choose_language": "Choose Language",
        "upcoming_trip_details": "Upcoming Trip Details",
        "cancel_ride": "Cancel Ride",
        "wallet": "Wallet",
        "your_wallet_amount": "Your Wallet Amount",
        "add_money": "Add Money",
        "add_amount": "Add Amount",
        "please_enter_amount": "Please enter amount",
        "Please_enter_more_when_amount": "Please enter more then 0 amount",
        "your_trips": "Your Trips",
        "no_past_Trips_found": "No Past Trips found",
        "no_upcoming_trips_found": "No upcoming trips found",
        "cancel": "Cancel",
        "add_card_for_payments": "Add card for payments",
        "card_number": "Card Number",
        "expiration_date": "Expiration Date",
        "add_card": "Add Card",
        "please_insert_valid_expiry_date": "Please insert valid expiry date",
        "change_password": "Change\nPassword",
        "current_password": "Current Password",
        "chat": "Chat",
        "loading...": "Loading...",
        "type_something_here": "Type Something Here",
        "from_to": "From To",
        "where_to?": "Where To?",
        "apply_coupon": "Apply Coupon",
        "view_code": "View Code",
        "request": "Request",
        "rate_card": "Rate Card",
        "fare /": "Fare /",
        "fare_type": "Fare Type",
        "capacity": "Capacity",
        "schedule_a_ride": "Schedule a ride",
        "choose_a_date": "Choose a date",
        "please_select_date": "Please Select date",
        "please_select_time": "Please Select time",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Cancel Trip",
        "eta": "ETA",
        "share_status": "Share Status",
        "location_permissions_are_denied": "Location permissions are denied",
        "allow": "Allow",
        "kms": "Kms",
        "where_to": "Where To",
        "pick_from_map": "Pick From Map",
        "round_trip": "Round Trip",
        "location_permissions_denied": "Location permissions are denied",
        "payment": "Payment",
        "apply_coupan": "Apply Coupan",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% Off Max discount is 50",
        "valid_Till_13,June_2021": "valid Till : 13,June 2021",
        "view_Code": "View Code",
        "case": "Cash",
        "location_denied": "Location permissions are denied",
        "payments": "Payments",
        "offer": "Offer",
        "settings": "Settings",
        "notification_manger": "Notification Manger",
        "share": "Share",
        "invite_Friend": "Invite Friend",
        "logout": "Logout",
        "choose_onew": "Choose one",
        "hey_User": "Hey Checkout this app, Touk Touk",
        "use_wallet": "Use Wallet",
        "past_rides": "Past rides",
        "account": "Account",
        "where_would-you_like_to_go?": "Where would you like to go?",
        "other": "Other",
        "enter_destination": "Enter Destination",
        "past": "Past",
        "upcoming": "Upcoming",
        "touk_touk_credit_balance": "Touk Touk Credit Balance",
        "saved_addresses": "Saved Addresses",
        "saved_contacts": "Saved Contacts",
        "change_language": "Change language",
        "hindi": "Hindi",
        "from:": "From:",
        "to:": "To:",
        "home_destination_is_not_added": "Home destination is not added",
        "work_destination_is_not_added": "Work destination is not added",
        "address_is_not_added": "Address is not added",
        "recent_locations": "Recent locations",
        "trip_details": "Trip Details",
        "source": "Source",
        "destination": "Destination",
        "select_car": "Select car",
        "myself": "MySelf",
        "coupons": "Coupons",
        "driver_is_arriving...": "Driver is Arriving...",
        "driver_has_arrived.": "Driver has Arrived.",
        "your_ride_has_started": "Your ride has started",
        "arrival": "Arrival",
        "rate_driver": "Rate Driver",
        "someone_else_taking_the_ride?": "Someone else taking the ride?",
        "choose a contact so that they also get driver number, vehicle details and ride OTP via SMS":
            "Choose a contact so that they also get driver number, vehicle details and ride OTP via SMS",
        "book_for_someone": "Book for someone",
        "book_for_someone_else": "Book for someone else",
        "payment_methods": "Payment Methods",
        "online(UPI, Card, Net banking)": "Online(UPI, Card, Net banking)",
        "how_is_your_driver?": "How is your driver?",
        "please_rate_your_driver": "Please rate your driver",
        "feedback_for_the_driver": "Feedback for the driver",
        "delete_account": "Delete\nAccount",
        "pick_contact": "Pick Contact",
        "save_contact": "Save Contact",
        "together_we are": "Together, we\'re growing\nStronger and further",
        "refer_now_and_earn": "Refer now amd earn",
        "referral_code": "Referral code",
        "or": "Or",
        "share_your_link_via": "Share your link via",
        "spread the word, And we will reward you":
            "Spread the word, And we will reward you",
        "get INR 100 in your Eto wallet for every friend you refer":
            "Get INR 100 in your Eto wallet for every friend you refer",
        "referral Count": "Referral Count",
        "Referral Amount": "Referral Amount",
        "Tell_us_your_experience_with_touk_touk": "Tell us your experience with Touk Touk",
        "hi": "hi ",
        "Write_something": "Write something.....",
        "Skip": "Skip",
        "No": "No",
        "Yes": "Yes",
        "add_details": "Add details",
        "note_added": "Note added successfully",
        "add_task_details": "Add task Details",
        "drop_off_by": "Drop off by",
        "you_deserve_best_driver": "You deserve the best, Conecting you with the best driver",
        "congratulations": "Congratulations",
        "you_have_successfully": "You have successfully",
        "completed": "completed ",
        "trips_with": " trips with",
        "touk_touk": "Touk Touk",
        "you_are_now_a_verified": "You are now a verified driver on Touk Touk",
        "All_users_will": "All users will be able to see the",
        "verification_green_tick": "Verification green tick ",
        "in_front_of_your_name": "in front of your name",
        "keep_Riding": "Keep Riding with us, We value your trust placed on us",
        "taxi": 'taxi',
        "delivery": "delivery",
        "email(optional)": "Email (optional)",
        "email id (not added)": "email id (not added)",
        "join_us": "Join Us Via Phone Number",
        "enter_yor_phone": "Enter your phone number"
      },
      "hi_IN": {
        "Sorry_for_the_technical_Beakdown" :
        "तकनीकी खराबी की समस्या के लिए क्षमा करें। हम यहां आपकी सहायता के लिए उपलब्ध हैं। जब तक हम समाधान करते हैं कृपया प्रतीक्षा करें।",
    "No": "नहीं",
    "Yes": "हां",
        "payment_back":"आपका लेन-देन प्रक्रियाधीन है, क्या आप सुनिश्चित हैं कि आप इस टैब को बंद करना चाहते हैं?",
        "Skip": "छोड़ें",
        "Tell_us_your_experience_with_touk_touk": "Touk Touk के साथ अपना अनुभव हमें बताएं",
        "Write_something": "कुछ लिखेंगे.....",
        "You_deserve_the_best_Connecting_you_with_the_best_driver":
            "आप सबसे अच्छे के लायक हैं, आपको सबसे अच्छे ड्राइवर से जोड़ते हैं",
        "Dont_have": "अब तक कोई खाता नहीं है?",
        "language": "हिन्दी",
        "forgot_password": " पासवर्ड भूल गए ",
        "otp": " ओटीपी ",
        "verification_code": "पुष्टि संख्या",
        "new_password": " नया पासवर्ड ",
        "confirm_new_password": " नए पासवर्ड की पुष्टि करें ",
        "submit": " प्रस्तुत करना ",
        "Please_type_the_verification_code_sent_to_your":
            "कृपया आपके पर भेजा गया सत्यापन कोड टाइप करें",
        "mobile_number": "मोबाइल नंबर",
        "Please_type_the_verification_code_sent_to_your_email":
            "कृपया आपके ईमेल पर भेजा गया सत्यापन कोड टाइप करें",
        "please_enter_otp": " कृपया ओटीपी दर्ज करें ",
        "wrong_otp": " गलत ओटीपी ",
        "please_enter_password": " कृप्या पास्वर्ड भरो ",
        "password_length": " पासवर्ड की लंबाई 6-15 अक्षरों के बीच होनी चाहिए.",
        "password_should_be_same": " पासवर्ड समान होना चाहिए ",
        "welcome_back": " वापसी पर स्वागत है ",
        "email": " ईमेल ",
        "password": " पासवर्ड ",
        "log_in": " लॉग इन करें ",
        "don't_have_an_account?": " खाता नहीं है?",
        "register": " पंजीकरण करवाना ",
        "Please_type_the_verification_code_sent_to_your":
            " कृपया सत्यापन कोड टाइप करें\nआपके पास भेजा गया ",
        "continue": " जारी रखना ",
        "please_enter_valid_otp": " कृपया मान्य ओटीपी दर्ज करें ",
        "didn_t_get_the_OTP": " ओटीपी नहीं मिला? ",
        "resend_OTP": " ओटीपी पुनः भेजें ",
        "enter_phone": " जारी रखने के लिए फ़ोन नंबर दर्ज करें ",
        "phone": " फ़ोन ",
        "please_number.": " अपना मोबाइल नंबर दर्ज करें.",
        "check_fare": " किराया जांचें ",
        "sign_up": " साइन अप करें ",
        "Or_continue_with": " या साथ जारी रखें ",
        "create_account": " खाता बनाएं ",
        "first_name": " पहला नाम ",
        "last_name": " उपनाम ",
        "confirm_password": " पासवर्ड की पुष्टि कीजिये ",
        "i_have_read": " मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं.",
        "terms_condition": " नियम एवं शर्तें ",
        "sign_in": " साइन इन करें ",
        "Don't-have_account?": " खाता नहीं है?",
        "are_sure_delete?": " क्या आप वाकई मिटाना चाहते हैं?",
        "no": " ना ",
        "delete": " मिटाना ",
        "no_data_found..": " कोई डेटा नहीं मिला..",
        "valid_till": " तक मान्य है ",
        "remove": " हटाना ",
        "use_code": " कोड का प्रयोग करें ",
        "dispute": " विवाद ",
        "you": " आप ",
        "admin": " व्यवस्थापक ",
        "driver_unprofessional": " चालक अव्यवसायिक ",
        "something_went_wrong...": " कुछ गलत हो गया...",
        "please_dispute..": " कृपया कोई विवाद चुनें..",
        "dismiss": " नकार देना ",
        "finding_driver...": " ड्राइवर ढूंढ रहा है...",
        "cancel_request": " अनुरोध रद्द ",
        "invoice": " इनवॉइस ",
        "booking_id": "बुकिंग आईडी ",
        "time-Taken": " समय लिया ",
        "base_fare": " बुनियादी भाड़ा",
        "time_fare": " समय किराया ",
        "distance_fare": " दूरी किराया ",
        "waiting_amount": " प्रतीक्षा राशि",
        "toll_charges": " टोल शुल्क ",
        "tips": " सलाह ",
        "add_tip": " युक्ति जोड़ें ",
        "total": " कुल ",
        "wallet_detection": " वॉलेट का पता लगाना ",
        "round_off": " पूर्णांक करना ",
        "discount": " छूट",
        "payable": " देय ",
        "payment_:_": " भुगतान : ",
        "change": " परिवर्तन ",
        "payment_driver": " ड्राइवर पार्टनर से भुगतान की पुष्टि नहीं हुई ",
        "done": " पूर्ण ",
        "pay_now": "अब भुगतान करें ",
        "lost_item": " खोई हुई वस्तु ",
        "Mention_the_lost_item": " खोई हुई वस्तु का उल्लेख करें ",
        "please_details": " कृपया खोई हुई वस्तु का विवरण दर्ज करें ",
        "ratings_your_trip_with": " के साथ अपनी यात्रा का मूल्यांकन करें ",
        "write_your_comment": " अपनी टिप्पणी लिखें ",
        "reason_for_canceling": " रद्द करने का कारण ",
        "scan_the_number":
            " मोबाइल नंबर प्राप्त करने के लिए क्यूआर स्कैन करें ",
        "sos_alert": " आपात स्थिति अलर्ट ",
        "are_you_sure_alert?":
            " क्या आप वाकई आपातकालीन चेतावनी के साथ आगे बढ़ना चाहते हैं?",
        "yes": " हां ",
        "time_taken": " समय लिया ",
        "tax": " कर ",
        "close": " बंद करना ",
        "help": "मदद",
        "support": " सहायता ",
        "call": " बुलाना ",
        "message": " संदेश ",
        "our_you_soon!": " हमारी टीम के लोग जल्द ही आपसे संपर्क करेंगे!",
        "invite_friend": "मित्र को न्योता ",
        "your_referral_code": " आपका रेफरल कोड ",
        "choose_one": " एक का चयन ",
        "referral_count :": " रेफरल काउंट:",
        "referral_amount:": " रेफरल राशि:",
        "notification_manager": " अधिसूचना प्रबंधक ",
        "you_any_notification": " आपके पास कोई सूचना नहीं है ",
        "passbook": " पासवृक ",
        "no_wallet_history": " कोई बटुआ इतिहास नहीं ",
        "amount": " राशि ",
        "balance": " संतुलन: ",
        "lost_my_item": " मेरी वस्तु खो गई ",
        "past_trip_details": " पिछली यात्रा का विवरण ",
        "pay_via": " माध्यम से भुगतान करें ",
        "comments": "टिप्पणियाँ ",
        "no_comments": " कोई टिप्पणी नहीं ",
        "view_receipt": " रसीद देखें ",
        "open": " खोलना ",
        "payment_options": " भुगतान विकल्प ",
        "cash": " नकद ",
        "by_cash": " नकद द्वारा ",
        "card": " कार्ड ",
        "add": " जोड़ें ",
        "payStack": " PayStack ",
        "profile": " प्रोफ़ाइल ",
        "phone_number": " फ़ोन नंबर ",
        "looking_to_change_password": " पासवर्ड बदलना चाह रहे हैं ",
        "save": " बचाना ",
        "setting": " स्थापना ",
        "favorites": " पसंदीदा ",
        "home": " घर ",
        "work": " काम ",
        "choose_language": "भाषा चुनें ",
        "upcoming_trip_details": " आगामी यात्रा विवरण ",
        "cancel_ride": " राइड रद्द करें ",
        "wallet": " बटुआ ",
        "your_wallet_amount": " बटुआ ",
        "add_money": " पैसे जोड़ें ",
        "add_amount": " राशि जोड़ें ",
        "please_enter_amount": " कृपया राशि दर्ज करें ",
        "Please_enter_more_when_amount": " कृपया 0 से अधिक राशि दर्ज करें ",
        "your_trips": " आपकी यात्राएं ",
        "no_past_Trips_found": " कोई पिछली यात्राएं नहीं मिलीं ",
        "no_upcoming_trips_found": " कोई आगामी ट्रिप नहीं मिली ",
        "cancel": " रद्द करना ",
        "add_card_for_payments": " भुगतान के लिए कार्ड जोड़ें ",
        "card_number": " कार्ड नंबर ",
        "expiration_date": " समाप्ति तिथि ",
        "add_card": " कार्ड जोड़ें ",
        "please_insert_valid_expiry_date": " कृपया मान्य समाप्ति तिथि डालें ",
        "change_password": " पासवर्ड\nबदलें ",
        "current_password": " वर्तमान पासवर्ड ",
        "chat": " बात करना ",
        "loading...": " लोड हो रहा है...",
        "type_something_here": " यहाँ कुछ टाइप करें ",
        "from_to": " से ",
        "where_to?": " जहां?",
        "apply_coupon": " कूपन लागू करें ",
        "view_code": " कोड देखें ",
        "request": "अनुरोध ",
        "rate_card": " दर कार्ड ",
        "fare /": " किराया /",
        "fare_type": " किराए का प्रकार ",
        "capacity": " क्षमता ",
        "schedule_a_ride": " राइड शेड्यूल करें ",
        "choose_a_date": " एक तिथि चुनें ",
        "please_select_date": " कृपया तिथि चुनें ",
        "please_select_time": " कृपया समय चुनें ",
        "sos": " मुसीबत का इशारा ",
        "otp:": " ओटीपी: ",
        "cancel_trip": " यात्रा रद्द करें ",
        "eta": "",
        "share_status": " शेयर स्थिति ",
        "location_permissions_are_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "allow": " अनुमति देना ",
        "kms": " किलोमीटर ",
        "where_to": " जहां ",
        "pick_from_map": " मानचित्र से चुनें ",
        "round_trip": " राउंड ट्रिप ",
        "location_permissions_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "payment": " भुगतान ",
        "apply_coupan": " कूपन लागू करें ",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "अधिकतम छूट पर 10% की छूट 50 है",
        "valid_Till_13,June_2021": " तक वैध: 13, जून 2021",
        "view_Code": " कोड देखें ",
        "case": " नकद ",
        "location_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "payments": " भुगतान ",
        "offer": " प्रस्ताव ",
        "settings": "समायोजन ",
        "notification_manger": "सूचना प्रबंधक ",
        "share": "शेयर करना ",
        "invite_Friend": "मित्र को न्योता ",
        "logout": "लॉग आउट ",
        "choose_onew": " एक का चयन ",
        "hey_User": " अरे इस ऐप को चेकआउट करें, Touk Touk ",
        "use_wallet": " वॉलेट का प्रयोग करें ",
        "hi": " नमस्ते ",
        "past_rides": "पिछली सवारी",
        "account": "खाता",
        "where_would-you_like_to_go?": "आप कहां जाना चाहाेगे?",
        "other": "अन्य",
        "enter_destination": "गंतव्य दर्ज करें",
        "your_trips": "आपकी यात्राएं",
        "past": "अतीत",
        "upcoming": "आगामी",
        "add_amount": "राशि जोड़ें",
        "touk_touk_credit_balance": "Touk Touk क्रेडिट बैलेंस",
        "past_rides": "पिछली सवारी",
        "saved_addresses": "सहेजे गए पते",
        "saved_contacts": "सहेजे गए संपर्क",
        "change_language": "भाषा बदलो",
        "hindi": "हिन्दी",
        "from:": "से:",
        "to:": "प्रति:",
        "home_destination_is_not_added": "गृह गंतव्य जोड़ा नहीं गया है",
        "work_destination_is_not_added": "कार्य गंतव्य नहीं जोड़ा गया है",
        "address_is_not_added": "पता नहीं जोड़ा गया है",
        "recent_locations": "हाल के स्थान",
        "trip_details": "यात्रा विवरण",
        "source": "स्रोत",
        "destination": "गंतव्य",
        "select_car": "कार चुनें",
        "myself": "खुद",
        "coupons": "कूपन",
        "driver_is_arriving...": "ड्राइवर आ रहा है...",
        "driver_has_arrived.": "ड्राइवर आ गया है.",
        "your_ride_has_started": "आपकी सवारी शुरू हो गई है.",
        "arrival": "आगमन",
        "rate_driver": "ड्राइवर रेटिंग",
        "someone_else_taking_the_ride?": "कोई और सवारी कर रहा है?",
        "choose a contact so that they also get driver number, vehicle details and ride OTP via SMS":
            "एक संपर्क चुनें ताकि उन्हें चालक संख्या, विवरण के पीछे और एसएमएस के माध्यम से ओटीपी प्राप्त हो सके",
        "book_for_someone": "किसी के लिए बुक",
        "book_for_someone_else": "सहेजे गए संपर्क",
        "payment_methods": "भुगतान की विधि",
        "online(UPI, Card, Net banking)": "ऑनलाइन (यूपीआई, कार्ड, नेट बैंकिंग)",
        "how_is_your_driver?": "आपका ड्राइवर कैसा है?",
        "please_rate_your_driver": "कृपया अपने ड्राइवर को रेट करें",
        "feedback_for_the_driver": "ड्राइवर के लिए प्रतिक्रिया",
        "delete_account": "खाता\nहटा दो",
        "pick_contact": "संपर्क उठाओ",
        "save_contact": "संपर्क सहेज",
        "together_we are": "एक साथ, हम मजबूत\nऔर आगे बढ़ रहे हैं",
        "refer_now_and_earn": "अभी रेफर करें और कमाएं",
        "referral_code": "रेफरल कोड",
        "or": "या",
        "share_your_link_via": "के माध्यम से अपना लिंक साझा करें",
        "spread the word, And we will reward you":
            "प्रचार करें, और हम आपको पुरस्कृत करेंगे",
        "get INR 100 in your Eto wallet for every friend you refer":
            "आपके द्वारा संदर्भित प्रत्येक मित्र के लिए अपने Eto वॉलेट में INR 100 प्राप्त करें",
        "Referral Count": "रेफरल गिनती",
        "Referral Amount": "रेफरल राशि"
      },
      "nl_NL": {
        "language": "Dutch",
        "forgot_password": "Wachtwoord vergeten",
        "otp": "OTP",
        "new_password": "nieuw paswoord",
        "confirm_new_password": "Bevestig nieuw wachtwoord",
        "submit": "Indienen",
        "please_enter_otp": "Voer alstublieft OTP in",
        "wrong_otp": "Verkeerde OTP",
        "please_enter_password": "Voer wachtwoord in alstublieft",
        "password_length":
            "De lengte van het wachtwoord moet tussen 6-15 tekens zijn.",
        "password_should_be_same": "Wachtwoord moet hetzelfde zijn",
        "welcome_back": "Welkom Rug",
        "email": "E-mail",
        "password": "Wachtwoord",
        "log_in": "Log In",
        "don't_have_an_account?": "Heb je geen account?",
        "register": "Register",
        "verification_code": "Verificatie code",
        "Please_type_the_verification_code_sent_to_your":
            "Typ de verificatiecode a.u.b.\nverzonden naar uw",
        "continue": "Doorgaan",
        "please_enter_valid_otp": "Vul a.u.b. geldige otp in",
        "didn`t_get_the_OTP": "heb de OTP niet gekregen",
        "resend_OTP": "RESEND OTP",
        "enter_phone": "OTP OPNIEUW VERZENDEN",
        "phone": "Telefoon",
        "please_number.": "Voer alstublieft uw mobiele nummer in.",
        "check_fare": "Controleer tarief",
        "sign_up": "Aanmelden",
        "Or_continue_with": "Of Ga verder met",
        "create_account": "Creëren\nAccount",
        "first_name": "Voornaam",
        "last_name": "Achternaam",
        "confirm_password": "bevestig wachtwoord",
        "i_have_read":
            "Ik heb de voorwaarden gelezen en ga ermee akkoord en\nConditie.",
        "terms_condition": "Algemene voorwaarden",
        "sign_in": "Log in",
        "Don't-have_account?": "Don't have an account?",
        "are_sure_delete?": "Weet je zeker dat je wilt verwijderen?",
        "no": "NEE",
        "delete": "VERWIJDEREN",
        "no_data_found..": "Geen data gevonden..",
        "valid_till": "geldig tot",
        "remove": "Verwijderen",
        "use_code": "Gebruik code",
        "dispute": "Onenigheid",
        "you": "Jij",
        "admin": "beheerder",
        "driver_unprofessional": "Bestuurder onprofessioneel",
        "something_went_wrong...": "Er is iets fout gegaan...",
        "please_dispute..": "Selecteer een geschil..",
        "dismiss": "Afwijzen",
        "finding_driver...": "Bestuurder zoeken...",
        "cancel_request": "Annuleringsaanvraag.",
        "invoice": "Factuur",
        "time-Taken": "Tijd genomen",
        "base_fare": "Basistarief",
        "time_fare": "Tijdtarief",
        "distance_fare": "Afstand tarief",
        "waiting_amount": "Wachtbedrag",
        "toll_charges": "Tolkosten",
        "tips": "Tips",
        "add_tip": "Tip toevoegen",
        "total": "Totaal",
        "wallet_detection": "Portemonnee detectie",
        "discount": "Korting",
        "payable": "te betalen",
        "payment_:_": "Betaling :",
        "change": "WIJZIGEN",
        "payment_driver": "Betaling niet bevestigd door de chauffeur",
        "done": "Gedaan",
        "pay_now": "Nu betalen",
        "lost_item": "Verloren voorwerp",
        "Mention_the_lost_item": "Vermeld het verloren voorwerp",
        "please_details": "Voer details van verloren voorwerpen in",
        "ratings_your_trip_with": "Beoordeelt uw reis met",
        "write_your_comment": "Schrijf je commentaar",
        "reason_for_canceling": "Reden van annuleren",
        "scan_the_number": "Scan de QR om het mobiele nummer op te halen",
        "sos_alert": "SOS-melding",
        "are_you_sure_alert?":
            "Weet u zeker dat u door wilt gaan met een noodwaarschuwing?",
        "yes": "JA",
        "booking_id": "Boekings-ID",
        "time_taken": "Tijd genomen",
        "tax": "Belasting",
        "round_off": "Afronden",
        "close": "Dichtbij",
        "help": "Helpen",
        "support": "Steun",
        "call": "Telefoongesprek",
        "message": "Bericht",
        "our_you_soon!": "Onze teamleden nemen spoedig contact met u op!",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Uw verwijzingscode",
        "choose_one": "kies er een",
        "referral_count :": "Aantal verwijzingen:",
        "referral_amount:": "Verwijzingsbedrag:",
        "notification_manager": "Meldingsmanager",
        "you_any_notification": "Je hebt geen melding",
        "passbook": "Passbook",
        "no_wallet_history": "Geen portemonnee-geschiedenis",
        "amount": "Hoeveelheid",
        "balance": "Evenwicht :",
        "lost_my_item": "Mijn item verloren",
        "past_trip_details": "Eerdere reisdetails",
        "pay_via": "Betalen via",
        "comments": "Opmerkingen",
        "no_comments": "Geen reacties",
        "view_receipt": "Bekijk bon",
        "open": "OPEN",
        "payment_options": "Betalingsmogelijkheden",
        "cash": "CONTANT GELD",
        "by_cash": "Contant",
        "card": "Kaart",
        "add": "Toevoegen",
        "payStack": "PayStack",
        "profile": "Profiel",
        "phone_number": "Telefoonnummer",
        "looking_to_change_password": "Op zoek naar wachtwoord wijzigen",
        "save": "Opslaan",
        "setting": "Instelling",
        "favorites": "Favorieten",
        "home": "Huis",
        "work": "Werk",
        "choose_language": "Kies een taal",
        "upcoming_trip_details": "Aankomende reisdetails",
        "cancel_ride": "Rit annuleren",
        "wallet": "Portemonnee",
        "your_wallet_amount": "Uw Wallet-bedrag",
        "add_money": "Voeg geld toe",
        "add_amount": "Bedrag toevoegen",
        "please_enter_amount": "Vul a.u.b. bedrag in",
        "Please_enter_more_when_amount": "Vul a.u.b. meer dan 0 bedrag in",
        "your_trips": "Uw reizen",
        "no_past_Trips_found": "Geen eerdere reizen gevonden",
        "no_upcoming_trips_found": "Geen aankomende reizen gevonden",
        "cancel": "Annuleren",
        "add_card_for_payments": "Kaart toevoegen voor betalingen",
        "card_number": "Kaartnummer",
        "expiration_date": "vervaldatum",
        "add_card": "Voeg een kaart toe",
        "please_insert_valid_expiry_date": "Voer een geldige vervaldatum in",
        "change_password": "Verander wachtwoord",
        "current_password": "huidi wachtwoord",
        "chat": "Chatten",
        "loading...": "Bezig met laden...",
        "type_something_here": "Typ hier iets",
        "from_to": "Van naar",
        "where_to?": "Waarheen?",
        "apply_coupon": "gebruik coupon",
        "view_code": "Bekijk code",
        "request": "Verzoek",
        "rate_card": "Tariefkaart",
        "fare /": "Tarief /",
        "fare_type": "Tarieftype",
        "capacity": "Capaciteit",
        "schedule_a_ride": "Plan een rit",
        "choose_a_date": "Kies een datum",
        "please_select_date": "Selecteer datum a.u.b.",
        "please_select_time": "Selecteer tijd a.u.b.",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Reis annuleren",
        "eta": "ETA",
        "share_status": "Deel status",
        "location_permissions_are_denied": "Locatierechten zijn geweigerd",
        "allow": "Toestaan",
        "kms": "km",
        "where_to": "Waarheen",
        "pick_from_map": "Kies uit kaart",
        "round_trip": "Rondvaart",
        "location_permissions_denied": "Locatierechten zijn geweigerd",
        "payment": "Betaling",
        "apply_coupan": "gebruik coupon",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% korting Max korting is 50",
        "valid_Till_13,June_2021": "geldig t/m : 13 juni 2021",
        "view_Code": "Bekijk code",
        "case": "CONTANT GELD",
        "location_denied": "Locatierechten zijn geweigerd",
        "payments": "Betalingen",
        "offer": "Bieden",
        "settings": "Instellingen",
        "notification_manger": "Meldingsmanager",
        "share": "Deel",
        "invite_Friend": "Nodig een vriend uit",
        "logout": "Uitloggen",
        "choose_onew": "Kies er een",
        "hey_User": "Hey Check deze app, Touk Touk-gebruiker",
        "use_wallet": "Portemonnee gebruiken",
      },
      "es_SP": {
        "Sorry_for_the_technical_Beakdown" :
        "Perdón por el problema de avería técnica. Estamos aquí para ayudarte. por favor espere mientras resolvemos.",
        "payment_back":"Su transacción está en proceso. ¿Está seguro de que desea cerrar esta pestaña?",
        "Dont_have": "¿Todavía no tienes una cuenta?",
        "language": "Spanish",
        "forgot_password": "Has olvidado tu contraseña",
        "otp": "OTP",
        "new_password": "Nueva contraseña",
        "confirm_new_password": "Confirmar nueva contraseña",
        "submit": "Entregar",
        "please_enter_otp": "Por favor ingrese OTP",
        "wrong_otp": "OTP incorrecta",
        "please_enter_password": "Por favor, ingrese contraseña",
        "password_length": "La longitud de la contraseña debe tener entre 6 y 15 caracteres.",
        "password_should_be_same": "La contraseña debe ser la misma",
        "welcome_back": "Bienvenido de nuevo",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "log_in": "Acceso",
        "don't_have_an_account?": "¿No tienes una cuenta?",
        "register": "Registro",
        "verification_code": "Código de verificación",
        "You_deserve_the_best_Connecting_you_with_the_best_driver":
        "Te mereces lo mejor, Conectándote con el mejor conductor",
        "continue": "Continuar",
        "please_enter_valid_otp": "Ingrese otp válido",
        "didn_t_get_the_OTP": "¿No recibió la OTP?",
        "resend_OTP": "REENVIAR OTP ",
        "enter_phone": "Introduce el número de teléfono para continuar",
        "phone": "Teléfono",
        "Please_type_the_verification_code_sent_to_your":
        "Por favor, escriba el código de verificación enviado a su",
        "mobile_number": " Número de teléfono móvil",
        "Please_type_the_verification_code_sent_to_your_email":
        "Por favor, escriba el código de verificación enviado a su correo electrónico",
        "please_number.": "Por favor, introduzca su número de móvil.",
        "check_fare": "Consultar tarifa",
        "sign_up": "Inscribirse",
        "Or_continue_with": "O continuar con",
        "create_account": "Crear una cuenta",
        "first_name": "Nombre de pila",
        "last_name": "Apellido",
        "confirm_password": "confirmar Contraseña",
        "i_have_read": "He leído y acepto los Términos y Condiciones.",
        "terms_condition": "Términos y condiciones",
        "sign_in": "Iniciar sesión",
        "Don't-have_account?": "¿No tienes una cuenta?",
        "are_sure_delete?": "¿Estás segura de que quieres eliminar?",
        "no": "NO",
        "delete": "BORRAR",
        "no_data_found..": "Datos no encontrados..",
        "valid_till": "Válida hasta",
        "remove": "Eliminar",
        "use_code": "Código de uso",
        "dispute": "Disputar",
        "you": "Tú",
        "admin": "Administradora",
        "driver_unprofessional": "Conductora no profesional",
        "something_went_wrong...": "Algo salió mal...",
        "please_dispute..": "Seleccione cualquier disputa..",
        "dismiss": "Despedir",
        "finding_driver...": "Encontrar conductora ...",
        "cancel_request": "Cancelar petición",
        "invoice": "Factura",
        "booking_id": "ID de reserva",
        "time-Taken": "Tiempo tomado",
        "base_fare": "Tarifa base",
        "time_fare": "Tarifa horaria",
        "distance_fare": "Tarifa de distancia",
        "waiting_amount": "Monto en espera",
        "toll_charges": "Peajes",
        "tips": "Consejos",
        "add_tip": "Agregar sugerencia",
        "total": "Total",
        "wallet_detection": "Detección de billetera",
        "round_off": "Redondear",
        "discount": "Descuento",
        "payable": "Pagadera",
        "payment_:_": "Pago : ",
        "change": "CAMBIAR",
        "payment_driver": "Pago no confirmado por el conductor",
        "done": "Hecho",
        "pay_now": "Pagar ahora",
        "lost_item": "Objeto perdido",
        "Mention_the_lost_item": "Menciona el objeto perdido",
        "please_details": "Ingrese los detalles del artículo perdido",
        "ratings_your_trip_with": "Califica tu viaje con",
        "write_your_comment": "Escribe tu comentario",
        "reason_for_canceling": "Motivo de la cancelación",
        "scan_the_number": "Escanea el QR para obtener el número de móvil",
        "sos_alert": "alerta de SOS",
        "are_you_sure_alert?":
        "¿Está seguro de que desea continuar con la alerta de emergencia?",
        "yes": "YES",
        "time_taken": "Tiempo tomado",
        "tax": "Impuesto",
        "close": "Cerca",
        "help": "Ayuda",
        "support": "Apoyo",
        "call": "Llamar",
        "message": "Mensaje",
        "our_you_soon!": "¡Nuestros miembros del equipo se pondrán en contacto con usted pronto!",
        "invite_friend": "Invitar a un amigo",
        "your_referral_code": "Su código de referencia",
        "choose_one": "elige uno",
        "referral_count :": "Recuento de referencias:",
        "referral_amount:": "Cantidad de referencia:",
        "notification_manager": "Administrador de notificaciones",
        "you_any_notification": "no tienes ninguna notificación",
        "passbook": "Libreta de depósitos",
        "no_wallet_history": "Sin historial de billetera",
        "amount": "Cantidad",
        "balance": "Balance :",
        "lost_my_item": "perdí mi artículo",
        "past_trip_details": "Detalles de viajes anteriores",
        "pay_via": "Pagar a través de",
        "comments": "Comentarios",
        "no_comments": "Sin comentarios",
        "view_receipt": "Ver recibo",
        "open": "ABIERTA",
        "payment_options": "Opciones de pago",
        "cash": "Dinero",
        "by_cash": "En efectivo",
        "card": "Tarjeta",
        "add": "Agregar",
        "payStack": "pila de pago",
        "profile": "Perfil",
        "phone_number": "Número de teléfono",
        "looking_to_change_password": "Buscando cambiar contraseña",
        "save": "Ahorrar",
        "setting": "Configuración",
        "favorites": "Favoritas",
        "home": "Hogar",
        "work": "Trabajar",
        "choose_language": "Elige lengua",
        "upcoming_trip_details": "Detalles del próximo viaje",
        "cancel_ride": "Cancelar viaje",
        "wallet": "Billetera",
        "your_wallet_amount": "Billetera",
        "add_money": "Agregar dinero",
        "add_amount": "Añadir cantidad",
        "please_enter_amount": "Por favor ingrese la cantidad",
        "Please_enter_more_when_amount": "Por favor ingrese más de 0 cantidad",
        "your_trips": "tus viajes",
        "no_past_Trips_found": "No se encontraron viajes anteriores",
        "no_upcoming_trips_found": "No se han encontrado próximos viajes",
        "cancel": "Cancelar",
        "add_card_for_payments": "Agregar tarjeta para pagos",
        "card_number": "Número de tarjeta",
        "expiration_date": "Fecha de caducidad",
        "add_card": "Agregar tarjeta",
        "please_insert_valid_expiry_date": "Por favor, inserte una fecha de caducidad válida",
        "change_password": "Cambiar la contraseña",
        "current_password": "Contraseña actual",
        "chat": "Charlar",
        "loading...": "Cargando...",
        "type_something_here": "Escriba algo aquí",
        "from_to": "Desde Hasta",
        "where_to?": "¿A donde?",
        "apply_coupon": "Aplicar cupón",
        "view_code": "Ver código",
        "request": "Pedido",
        "rate_card": "Tarjeta de tarifa",
        "fare /": "Tarifa ",
        "fare_type": "Tipo de tarifa",
        "capacity": "Capacidad",
        "schedule_a_ride": "programar un viaje",
        "choose_a_date": "Elige una fecha",
        "please_select_date": "Seleccione la fecha",
        "please_select_time": "Por favor seleccione hora",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Cancelar viaje",
        "eta": "ETA",
        "share_status": "Comparta su estado",
        "location_permissions_are_denied": "Los permisos de ubicación están denegados",
        "allow": "Permitir",
        "kms": "Kms",
        "where_to": "A donde",
        "pick_from_map": "Seleccionar del mapa",
        "round_trip": "Ida y vuelta",
        "location_permissions_denied": "Los permisos de ubicación están denegados",
        "payment": "Pago",
        "apply_coupan": "Aplicar cupón",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% de descuento El descuento máximo es 50",
        "valid_Till_13,June_2021": "Válida hasta: 13 de junio de 2021",
        "view_Code": "Ver código",
        "case": "Dinero",
        "location_denied": "Los permisos de ubicación están denegados",
        "payments": "Pagos",
        "offer": "Oferta",
        "settings": "Ajustes",
        "notification_manger": "Administrador de notificaciones",
        "share": "Compartir",
        "invite_Friend": "Invitar a un amigo",
        "logout": "Cerrar sesión",
        "choose_onew": "Elige uno",
        "hey_User": "Hola Checkout esta aplicación, usuaria de Touk Touk",
        "use_wallet": "Usar billetera",
        "past_rides": "Paseos pasados",
        "account": "Cuenta",
        "where_would-you_like_to_go?": "¿Dónde te gustaría ir?",
        "other": "Otra",
        "enter_destination": "Introducir destino",
        "past": "Pasada",
        "upcoming": "Próxima",
        "eto_credit_balance": "Saldo de crédito Arby",
        "saved_addresses": "Direcciones guardadas",
        "saved_contacts": "Contactos guardados",
        "change_language": "Cambiar idioma",
        "hindi": "Hindi",
        "from:": "De:",
        "to:": "A:",
        "home_destination_is_not_added": "El destino de origen no se agrega",
        "work_destination_is_not_added": "El destino del trabajo no se agrega",
        "address_is_not_added": "No se agrega la dirección",
        "recent_locations": "Ubicaciones recientes",
        "trip_details": "Detalles del viaje",
        "source": "Fuente",
        "destination": "Destino",
        "select_car": "Seleccionar coche",
        "myself": "Mí mismo",
        "coupons": "Cupones",
        "driver_is_arriving...": "La conductora esta llegando ...",
        "driver_has_arrived.": "La conductora ha llegado.",
        "your_ride_has_started": "Tu viaje ha comenzado",
        "arrival": "Llegada",
        "rate_driver": "Conductor de tarifa",
        "someone_else_taking_the_ride?": "Someone else taking the ride?",
        "choose a contact so that they also get driver number, vehicle details and ride OTP via SMS":
        "Elija un contacto para que también obtenga el número de conductor, los detalles del vehículo y viaje OTP a través de SMS",
        "book_for_someone": "libro para alguien",
        "book_for_someone_else": "Reservar para otra persona",
        "payment_methods": "Métodos de pago",
        "online(UPI, Card, Net banking)": "En línea (UPI, tarjeta, banca neta)",
        "how_is_your_driver?": "Como esta tu conductora",
        "please_rate_your_driver": "Por favor califique su conductora",
        "feedback_for_the_driver": "Comentarios para el conductor",
        "delete_account": "Borrar cuenta",
        "pick_contact": "Elegir contacto",
        "save_contact": "Guardar contacto",
        "together_we are": "Juntos, estamos creciendo Más fuerte y más lejos",
        "refer_now_and_earn": "Refiera ahora y gane",
        "referral_code": "Código de referencia",
        "or": "Or",
        "share_your_link_via": "Comparte tu enlace a través de",
        "spread the word, And we will reward you":
        "Corre la voz, y te recompensaremos",
        "get INR 100 in your Eto wallet for every friend you refer":
        "Obtén INR 100 en tu billetera Eto por cada amiga que refieras",
        "referral Count": "Recuento de referencias",
        "Referral Amount": "Cantidad de referencia",
        "Tell_us_your_experience_with_ETO": "Cuéntanos tu experiencia con ETO",
        "hi": "Hola ",
        "Write_something": "Escribe algo.....",
        "Skip": "Saltar",
        "No": "No",
        "Yes": "Sí"
      },
      "ar_AE":{
        "login_with_pw": "تسجيل الدخول بكلمة مرور",
        "language": "إنجليزي",
        "forgot_password": "نسيت كلمة المرور",
        "otp": "OTP",
        "new_password": "كلمة مرور جديدة",
        "confirm_new_password": "تأكيد كلمة المرور الجديدة",
        "submit": "إرسال",
        "please_enter_otp": "الرجاء إدخال OTP",
        "wrong_otp": "خطأ OTP",
        "please_enter_password": "الرجاء إدخال كلمة المرور",
        "password_length": "يجب أن يكون طول كلمة المرور بين 6-15 حرفًا.",
        "password_should_be_same": "نسيت كلمة المرور0",
        "welcome_back": "نسيت كلمة المرور1",
        "email": "نسيت كلمة المرور2",
        "password": "نسيت كلمة المرور3",
        "log_in": "نسيت كلمة المرور4" ,
        "don't_have_an_account?": "ليس لديك حساب؟",
        "register": "يسجل",
        "verification_code": "رمز التحقق",
        "Please_type_the_verification_code_sent_to_your": "الرجاء كتابة رمز التحقق المرسل إلى الخاص بك",
        "continue": "يكمل",
        "please_enter_valid_otp": "الرجاء إدخال otp صالح",
        "didn`t_get_the_OTP": "لم أحصل على OTP",
        "resend_OTP": "إعادة إرسال OTP",
        "enter_phone": "أدخل رقم الهاتف للمتابعة",
        "phone": "هاتف",
        "please_number.": "الرجاء إدخال رقم هاتفك المحمول.",
        "check_fare": "تحقق من الأجرة",
        "sign_up": "اشتراك",
        "Or_continue_with": "أو تواصل مع",
        "create_account": "إصنع حساب",
        "first_name": "الاسم الاول",
        "last_name": "الكنية",
        "confirm_password": "تأكيد كلمة المرور",
        "i_have_read": "لقد قرأت ووافقت على الشروط والأحكام.",
        "terms_condition": "البنود و الظروف",
        "sign_in": "تسجيل الدخول",
        "Don't-have_account?": "ليس لديك حساب؟",
        "are_sure_delete?": "هل أنت متأكد أنك تريد الحذف؟",
        "no": "رقم",
        "delete": "حذف",
        "no_data_found..": ".لاتوجد بيانات",
        "valid_till": "صالح لغاية",
        "remove": "إزالة",
        "use_code": "استخدم الكود",
        "dispute": "خلاف",
        "you": "أنت",
        "admin": "مسؤل",
        "driver_unprofessional": "سائق غير محترف",
        "something_went_wrong...": "هناك خطأ ما...",
        "please_dispute..": "الرجاء تحديد أي نزاع",
        "dismiss": "رفض",
        "finding_driver...": "إيجاد سائق",
        "cancel_request": "إلغاء الطلب",
        "invoice": "فاتورة",
        "booking_id": "معرف الحجز",
        "time-Taken": "الوقت المستغرق",
        "base_fare": "صنع القاعدة",
        "time_fare": "أجرة الوقت",
        "distance_fare": "المسافة أجرة",
        "waiting_amount": "مبلغ الانتظار",
        "toll_charges": "رسوم لعبور",
        "tips": "نصائح",
        "add_tip": "أضف نصيحة",
        "total": "المجموع",
        "wallet_detection": "كشف المحفظة",
        "round_off": "نهاية الجولة",
        "discount": "تخفيض",
        "payable": "مستحق الدفع",
        "payment_:_": "دفع ",
        "change": "يتغيرون",
        "payment_driver": "لم يتم تأكيد الدفع من السائق",
        "done": "فعله",
        "pay_now": "ادفع الآن",
        "lost_item": "فقدت البند",
        "Mention_the_lost_item": "اذكر العنصر المفقود",
        "please_details": "الرجاء إدخال تفاصيل العنصر المفقود",
        "ratings_your_trip_with": "تقييمات رحلتك مع",
        "write_your_comment": "اكتب تعليقك",
        "reason_for_canceling": "سبب الإلغاء",
        "scan_the_number": "امسح QR لجلب رقم الهاتف المحمول",
        "sos_alert": "إنذار الاستغاثة",
        "are_you_sure_alert?": "هل أنت متأكد أنك تريد المتابعة مع تنبيه الطوارئ؟",
        "yes": "نعم",
        "time_taken": "الوقت المستغرق",
        "tax": "ضريبة",
        "close": "قريب",
        "help": "مساعدة",
        "support": "الدعم",
        "call": "مكالمة",
        "message": "رسالة",
        "our_you_soon!": "سيتصل بك أفراد فريقنا قريبًا!",
        "invite_friend": "قم بدعوة صديق",
        "your_referral_code": "رمز الإحالة الخاص بك",
        "choose_one": "اختر واحدة",
        "referral_count :": "عدد الإحالة:",
        "referral_amount:": "مبلغ الإحالة:",
        "notification_manager": "مدير الإعلام",
        "you_any_notification": "ليس لديك أي إخطار",
        "passbook": "وصل الدفع",
        "no_wallet_history": "لا يوجد محفوظات المحفظة",
        "amount": "مقدار",
        "balance": "الرصيد  ",
        "lost_my_item": "فقدت البند الخاص بي",
        "past_trip_details": "تفاصيل الرحلة السابقة",
        "pay_via": "الدفع عن طريق",
        "comments": "تعليقات",
        "no_comments": "لا تعليق",
        "view_receipt": "استلام عرض",
        "open": "افتح",
        "payment_options": "خيارات الدفع",
        "cash": "السيولة النقدية",
        "by_cash": "نقدا",
        "card": "بطاقة",
        "add": "يضيف",
        "payStack": "PayStack",
        "profile": "الملف الشخصي",
        "phone_number": "رقم الهاتف",
        "looking_to_change_password": "تبحث لتغيير كلمة المرور",
        "save": "يحفظ",
        "setting": "ضبط",
        "favorites": "المفضلة",
        "home": "مسكن",
        "work": "عمل",
        "choose_language": "اختر اللغة",
        "upcoming_trip_details": "تفاصيل الرحلة القادمة",
        "cancel_ride": "إلغاء الركوب",
        "wallet": "محفظة",
        "your_wallet_amount": "مبلغ محفظتك",
        "add_money": "إضافة المال",
        "add_amount": "أضف المبلغ",
        "please_enter_amount": "الرجاء إدخال المبلغ",
        "Please_enter_more_when_amount": "الرجاء إدخال أكثر من 0 مبلغ",
        "your_trips": "رحلاتك",
        "no_past_Trips_found": "لم يتم العثور على رحلات سابقة",
        "no_upcoming_trips_found": "لم يتم العثور على رحلات قادمة",
        "cancel": "يلغي",
        "add_card_for_payments": "إضافة بطاقة للدفع",
        "card_number": "رقم البطاقة",
        "expiration_date": "تاريخ إنتهاء الصلاحية",
        "add_card": "إضافة بطاقة",
        "please_insert_valid_expiry_date": "الرجاء إدخال تاريخ انتهاء صالح",
        "change_password": "غير كلمة السر",
        "current_password": "كلمة المرور الحالية",
        "chat": "دردشة",
        "loading...": "جار التحميل",
        "type_something_here": "اكتب شيئًا هنا",
        "from_to": "من الى",
        "where_to?": "إلى أين؟",
        "apply_coupon": "تطبيق القسيمة",
        "view_code": "مشاهدة الكود",
        "request": "طلب",
        "rate_card": "سعر البطاقة",
        "fare /": "أجرة",
        "fare_type": "نوع عادل",
        "capacity": "الاهلية",
        "schedule_a_ride": "حدد موعدًا للرحلة",
        "choose_a_date": "اختر التاريخ",
        "please_select_date": "يرجى تحديد التاريخ",
        "please_select_time": "الرجاء تحديد الوقت",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "إلغاء الرحلة",
        "eta": "ETA",
        "share_status": "وضع حصة",
        "location_permissions_are_denied": "تم رفض أذونات الموقع",
        "allow": "السماح",
        "kms": "كم",
        "where_to": "إلى أين",
        "pick_from_map": "اختر من الخريطة",
        "round_trip": "ذهابا وإيابا",
        "location_permissions_denied": "تم رفض أذونات الموقع",
        "payment": "دفع",
        "apply_coupan": "تطبيق القسيمة",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10٪ خصم الحد الأقصى للخصم 50",
        "valid_Till_13,June_2021": "صالح حتى: 13 يونيو 2021",
        "view_Code": "مشاهدة الكود",
        "case": "السيولة النقدية",
        "location_denied": "تم رفض أذونات الموقع",
        "payments": "المدفوعات",
        "offer": "عرض",
        "settings": "الإعدادات",
        "notification_manger": "ممدير الإعلام",
        "share": "يشارك",
        "invite_Friend": "قم بدعوة صديق",
        "logout": "تسجيل خروج",
        "choose_onew": "اختر واحدة",
        "hey_User": "مرحبًا ، تحقق من هذا التطبيق ، مستخدم Mozlit",
        "use_wallet": "استخدم Wallet",
        "past_rides":"الرحلات الماضية",
        "saved_addresses":"العناوين المحفوظة",
        "account":"الحساب",
        "parcel":"قطعة",
        "ride":"اركب",
        "drop_off_by": "أنزل من قبل",
        "you_deserve_best_driver": "أنت تستحق الأفضل ، مع أفضل سائق",
        "congratulations": "تهانينا",
        "you_have_successfully": "لقد نجحت",
        "completed": "مكتمل",
        "trips_with": "رحلات مع",
        "touk_touk": "طوق طوك",
        "you_are_now_a_verified": "أنت الآن سائق معتمد على Touk Touk",
        "All_users_will": "سيتمكن جميع المستخدمين من رؤية ملف",
        "verification_green_tick": "التحقق من العلامة الخضراء",
        "in_front_of_your_name": "امام اسمك",
        "keep_Riding": "استمر في القيادة معنا ، نحن نقدر ثقتكم بنا",
        "taxi": 'سيارة اجره',
        "delivery": "توصيل",
        "email(optional)": "البريد الإلكتروني اختياري)",
        "email id (not added)": "معرف البريد الإلكتروني (غير مضاف)",
        "join_us": "انضم إلينا عبر رقم الهاتف",
        "enter_yor_phone": "أدخل رقم هاتفك",
        "didn_t_get_the_OTP": "ألم تحصل على OTP؟",
        "where_would-you_like_to_go?": "أين تريد أن تذهب؟",
        "enter_destination": "أدخل الوجهة",
        "delete_account": "حذف الحساب",
        "login_via_otp": "تسجيل الدخول عبر OTP",
      },
      "hy_AM": {
        "language": "Armenian",
        "login_via_otp": "Մուտք գործեք OTP-ի միջոցով",
        "login_with_pw": "Մուտք գործեք գաղտնաբառով",
        "forgot_password": "Մոռացել եք գաղտնաբառը",
        "otp": "օտպ",
        "new_password": "Նոր գաղտնաբառ",
        "confirm_new_password": "Հաստատեք նոր գաղտնաբառը",
        "submit": "Ներկայացնել",
        "please_enter_otp": "Խնդրում ենք մուտքագրել OTP",
        "wrong_otp": "Սխալ OTP",
        "please_confirm_password": "Խնդրում ենք մուտքագրել հաստատման գաղտնաբառը",
        "password_length": "Գաղտնաբառի երկարությունը պետք է լինի 6-15 նիշ:",
        "password_should_be_same": "Գաղտնաբառը պետք է լինի նույնը",
        "welcome_back": "Բարի վերադարձ",
        "email": "Էլ",
        "password": "Գաղտնաբառ",
        "log_in": "Մուտք գործեք",
        "don't_have_an_account?": "Չունե՞ք հաշիվ:",
        "register": "Գրանցվել",
        "verification_code": "Ստուգման կոդը",
        "Please_type_the_verification_code_sent_to_your": "Խնդրում ենք մուտքագրել ձեր հասցեին ուղարկված հաստատման կոդը",
        "continue": "Շարունակել",
        "please_enter_valid_otp": "Խնդրում ենք մուտքագրել վավեր otp",
        "didn`t_get_the_OTP": "չստացվեց OTP-ն",
        "resend_OTP": "ՎԵՐԱՍԱՐԿԵԼ OTP-ը",
        "enter_phone": "Շարունակելու համար մուտքագրեք հեռախոսահամարը",
        "phone": "Հեռախոս",
        "please_number.": "Խնդրում ենք մուտքագրել ձեր բջջային համարը:",
        "check_fare": "Ստուգեք ուղեվարձը",
        "sign_up": "Գրանցվել",
        "Or_continue_with": "Կամ Շարունակեք",
        "create_account": "Գրանցվել",
        "first_name": "Անուն",
        "last_name": "Ազգանուն",
        "confirm_password": "Հաստատել գաղտնաբառը",
        "i_have_read": "Ես կարդացել և համաձայնել եմ Պայմաններն ու դրույթները:",
        "terms_condition": "Պայմաններ եւ դրույթներ",
        "sign_in": "Մուտք գործել",
        "Don't-have_account?": "Չունե՞ք հաշիվ:",
        "are_sure_delete?": "Իսկապե՞ս ուզում եք ջնջել:",
        "no": "Ոչ",
        "delete": "ՋՆՋԵԼ",
        "no_data_found..": "Տվյալներ չեն գտնվել",
        "valid_till": "Վավերական է մինչև",
        "remove": "Հեռացնել",
        "use_code": "Օգտագործեք կոդը",
        "dispute": "Վեճ",
        "you": "Դուք",
        "admin": "Ադմին",
        "driver_unprofessional": "Վարորդը ոչ պրոֆեսիոնալ",
        "something_went_wrong...": "Ինչ որ բան այնպես չգնաց",
        "please_dispute..": "Խնդրում ենք ընտրել ցանկացած վեճ",
        "dismiss": "Հեռացնել",
        "finding_driver...": "Վարորդ գտնելը",
        "cancel_request": "Չեղարկել հարցումը",
        "invoice": "Հաշիվ-ապրանքագիր",
        "booking_id": "Ամրագրման ID",
        "time-Taken": "Վերցված ժամանակ",
        "base_fare": "Հիմքի պատրաստում",
        "time_fare": "Ժամանակի ուղեվարձ",
        "distance_fare": "Հեռավորության ուղեվարձ",
        "waiting_amount": "Սպասման գումարը",
        "toll_charges": "Վճարներ",
        "tips": "Խորհուրդներ",
        "add_tip": "Ավելացնել հուշում",
        "total": "Ընդամենը",
        "wallet_detection": "Դրամապանակի հայտնաբերում",
        "round_off": "Շուրջը",
        "discount": "Զեղչ",
        "payable": "Վճարովի",
        "payment_:_": "Վճարում : ",
        "change": "Փոփոխություն",
        "payment_driver": "Վարորդից վճարումը չի հաստատվել",
        "done": "Կատարած",
        "pay_now": "Վճարեք հիմա",
        "lost_item": "Կորած նյութ",
        "Mention_the_lost_item": "Նշեք կորած իրը",
        "please_details": "Խնդրում ենք մուտքագրել կորած ապրանքի մանրամասները",
        "ratings_your_trip_with": "Գնահատում է ձեր ճանապարհորդությունը",
        "write_your_comment": "Գրեք ձեր մեկնաբանությունը",
        "reason_for_canceling": "Չեղարկման պատճառը",
        "scan_the_number": "Սկանավորեք QR-ը՝ բջջային համարը ստանալու համար",
        "sos_alert": "SOS ազդանշան",
        "are_you_sure_alert?": "Վստա՞հ եք, որ ցանկանում եք շարունակել արտակարգ ծանուցումը:",
        "yes": "Այո՛",
        "time_taken": "Վերցված ժամանակ",
        "tax": "Հարկային",
        "close": "փակել",
        "help": "Օգնություն",
        "support": "Աջակցություն",
        "call": "Զանգահարեք",
        "message": "Հաղորդագրություն",
        "our_you_soon!": "Մեր թիմի աշխատակիցները շուտով կկապվեն ձեզ հետ:",
        "invite_friend": "Հրավիրեք ընկերոջը",
        "your_referral_code": "Ձեր ուղղորդման կոդը",
        "choose_one": "Ընտրիր մեկը",
        "referral_count :": "Ուղղորդման հաշվարկ :",
        "referral_amount:": "Ուղղորդման գումարը:",
        "notification_manager": "Ծանուցումների կառավարիչ",
        "you_any_notification": "Դուք որևէ ծանուցում չունեք",
        "passbook": "Անձնագիրք",
        "no_wallet_history": "Դրամապանակի պատմություն չկա",
        "amount": "Գումարը",
        "balance": "Հաշվեկշիռ : ",
        "lost_my_item": "Կորցրել եմ իմ իրը",
        "past_trip_details": "Անցյալ ուղևորության մանրամասները",
        "pay_via": "Վճարեք միջոցով",
        "comments": "Մեկնաբանություններ",
        "no_comments": "Առանց մեկնաբանությունների",
        "view_receipt": "Դիտել անդորրագիրը",
        "open": "ԲԱՑ",
        "payment_options": "Վճարման տարբերակներ",
        "cash": "ԿԱՆԽԻԿ",
        "by_cash": "Կանխիկով",
        "card": "Քարտ",
        "add": "Ավելացնել",
        "payStack": "PayStack",
        "profile": "Անձնագիր",
        "phone_number": "Հեռախոսահամար",
        "looking_to_change_password": "Փնտրում եմ փոխել գաղտնաբառը",
        "save": "Պահպանել",
        "setting": "Կարգավորում",
        "favorites": "Ֆավորիտներ",
        "home": "տուն",
        "work": "Աշխատանք",
        "choose_language": "Ընտրեք Լեզուն",
        "upcoming_trip_details": "Առաջիկա ուղևորության մանրամասները",
        "cancel_ride": "Չեղարկել Ուղևորությունը",
        "wallet": "Դրամապանակ",
        "your_wallet_amount": "Ձեր դրամապանակի գումարը",
        "add_money": "Գումար ավելացրեք",
        "add_amount": "Ավելացնել Գումար",
        "please_enter_amount": "Խնդրում ենք մուտքագրել գումարը",
        "Please_enter_more_when_amount": "Խնդրում ենք մուտքագրել 0-ից ավելի գումար",
        "your_trips": "Ձեր Ուղևորությունները",
        "no_past_Trips_found": "Անցյալ ուղևորություններ չեն գտնվել",
        "no_upcoming_trips_found": "Առաջիկա ուղևորություններ չեն գտնվել",
        "cancel": "Չեղարկել",
        "add_card_for_payments": "Ավելացրեք քարտ վճարումների համար",
        "card_number": "Քարտի համար",
        "expiration_date": "Սպառման ամսաթիվ",
        "add_card": "Ավելացնել քարտ",
        "please_insert_valid_expiry_date": "Խնդրում ենք մուտքագրել վավեր ժամկետը",
        "change_password": "Փոխել գաղտնաբառը",
        "current_password": "Ընթացիկ գաղտնաբառը",
        "chat": "զրուցել",
        "loading...": "Բեռնվում է",
        "type_something_here": "Մուտքագրեք ինչ-որ բան այստեղ",
        "from_to": "From To",
        "where_to?": "Ո՞ւր:",
        "apply_coupon": "Կիրառեք կտրոնը",
        "view_code": "Դիտել կոդը",
        "request": "Հայց",
        "rate_card": "Գնահատման քարտ",
        "fare /": "Ուղեվարձ /",
        "fare_type": "Ուղեվարձի տեսակը",
        "capacity": "Տարողություն",
        "schedule_a_ride": "Պլանավորեք զբոսանք",
        "choose_a_date": "Ընտրեք ամսաթիվ",
        "please_select_date": "Խնդրում ենք ընտրել ամսաթիվը",
        "please_select_time": "Խնդրում ենք ընտրել ժամանակը",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Չեղարկել ուղևորությունը",
        "eta": "ԵՎ",
        "share_status": "Համօգտագործման կարգավիճակը",
        "location_permissions_are_denied": "Տեղադրության թույլտվությունները մերժված են",
        "allow": "Թույլատրել",
        "kms": "կմ",
        "where_to": "Ուր Դեպի",
        "pick_from_map": "Ընտրեք քարտեզից",
        "round_trip": "Շրջագայություն",
        "location_permissions_denied": "Տեղադրության թույլտվությունները մերժված են",
        "payment": "Վճարում",
        "apply_coupan": "Կիրառեք կտրոնը",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% զեղչ Առավելագույն զեղչը կազմում է 50",
        "valid_Till_13,June_2021": "ուժի մեջ է մինչև 2021 թվականի հունիսի 13-ը",
        "view_Code": "Դիտել կոդը",
        "case": "ԿԱՆԽԻԿ",
        "location_denied": "Տեղադրության թույլտվությունները մերժված են",
        "payments": "Վճարումներ",
        "offer": "Առաջարկ",
        "settings": "Կարգավորումներ",
        "notification_manger": "Ծանուցման կառավարիչներ",
        "share": "Կիսվել",
        "invite_Friend": "Հրավիրեք ընկերոջը",
        "logout": "Դուրս գալ",
        "choose_onew": "Ընտրիր մեկը",
        "hey_User": "Hey Check out այս հավելվածը, Mozlit Userone",
        "use_wallet": "Օգտագործեք դրամապանակը",
        "hi": "Ողջու՜յն",
        "past_rides": "Անցյալ շրջագայություններ",
        "account": "Հաշիվներ",
        "parcel": "Ծանրոցներ",
        "ride": "Ուղևորություն",
        "source": "Աղբյուր",
        "destination": "Նպատակակետ",
        "select_car": "Ընտրեք Ավտոմեքենա",
        "trip_details": "Ուղևորության մանրամասները",
        "mozilit": "Mozilit",
        "add_task_details": "Ավելացրեք առաջադրանքի մանրամասները",
        "driver_is_arriving": "Վարորդը գալիս է...",
        "driver_has_arrived": "Վարորդը ժամանել է.",
        "ride_started": "Ձեր ճանապարհորդությունը սկսվել է:",
        "add_details": "Ավելացնել մանրամասներ",
        "note_added": "Նշումը հաջողությամբ ավելացվեց",
        "continuing_you_agree": "Շարունակելով՝ Դուք համաձայն եք մեր",
        "terms_of_use": "Օգտվելու կանոններ ",
        "and": "և",
        "or": "Կամ",
        "privacy_policy": " Գաղտնիության քաղաքականություն",
        "enter_first_name": "Մուտքագրեք անունը",
        "enter_last_name": "Մուտքագրեք ազգանունը",
        "create_an_account": "Ստեղծել հաշիվ",
        "offers": "Առաջարկներ",
        "delete_account": "Հաշիվը ջնջել",
        "active_now": "Ակտիվ հիմա",
        "type_something": "Մուտքագրեք ինչ-որ բան...",
        "from": "From:",
        "to": "դեպի՝",
        "enter_destination": "Մուտքագրեք նպատակակետը.",
        "work_destination_not_added": "Աշխատանքի նպատակակետը ավելացված չէ:",
        "home_destination_not_added": "Տնային նպատակակետն ավելացված չէ:",
        "recent_locations": "Վերջին վայրերը",
        "saved_addresses": "Պահպանված հասցեներ",
        "are_you_sure_logout": "Իսկապե՞ս ուզում եք դուրս գալ:",
        "enter_email": "Խնդրում ենք մուտքագրել ձեր էլ.փոստի հասցեն...",
        "payment_succesful": "Վճարումը հաջողությամբ ավարտվեց",
        "password_must_be_different": "Հին և նոր գաղտնաբառերը պետք է տարբեր լինեն",
        "enter_password": "Խնդրում ենք մուտքագրել գաղտնաբառը",
        "enter_current_password": "Խնդրում ենք մուտքագրել ընթացիկ գաղտնաբառը",
        "drop_off_by": "Բաց թողեք",
        "you_deserve_best_driver": "Դուք արժանի եք լավագույնին՝ Ձեզ կապելով լավագույն վարորդի հետ",
        "congratulations": "Շնորհավորում եմ",
        "you_have_successfully": "Դուք հաջողությամբ",
        "completed": "ավարտված",
        "trips_with": "հետ ճամփորդություններ",
        "touk_touk": "Թուկ Թուկ",
        "you_are_now_a_verified": "Դուք այժմ ստուգված վարորդ եք Touk Touk-ում",
        "All_users_will": "Բոլոր օգտվողները կկարողանան տեսնել",
        "verification_green_tick": "Ստուգման կանաչ տիզ",
        "in_front_of_your_name": "քո անվան դիմաց",
        "keep_Riding": "Շարունակեք վարել մեզ հետ, մենք գնահատում ենք ձեր վստահությունը, որը դրված է մեզ վրա",
        "taxi": "տաքսի",
        "delivery": "առաքում",
        "email(optional)": "Էլփոստ (ըստ ցանկության)",
        "email id (not added)": "էլփոստի id (ավելացված չէ)",
        "join_us": "Միացեք մեզ հեռախոսահամարով",
        "enter_yor_phone": "Մուտքագրեք ձեր հեռախոսահամարը",
        "didn_t_get_the_OTP": "Չե՞ք ստացել OTP-ն:",
        "where_would-you_like_to_go?": "Ուր եք ուզում գնալ?",

      }
    };
  }
}
